WebUI/WebUI/Models/Tasks.cs
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class Tasks
    {
        public int IdTask { get; set; }

        [Range(1, 999, ErrorMessage = "Debe seleccionar un colaborador!")]
        public int IdCollaborator { get; set; }

        public string? CollaboratorName { get; set; }

        [Required(ErrorMessage = "Campo requerido!")]
        public string? Description { get; set; }

        public string? Status { get; set; }

        public string? Priority { get; set; }

        [Required(ErrorMessage = "Fecha requerida!")]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FromDate { get; set; }
      
        [Required(ErrorMessage = "Fecha requerida!")]
        [DataType(DataType.Date)]
        public DateTime ToDate { get; set; }

        public string? Notes { get; set; }
    }

    public class TaskNew
    {
        public int IdTask { get; set; }
        public int IdCollaborator { get; set; }
        public string? Description { get; set; }
        public string? Status { get; set; }
        public string? Priority { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string? Notes { get; set; }
    }

    public class Priority
    {
        public int IdPriority { get; set; }
        public string? PriorityData { get; set; }
    }

    public class Status
    {
        public int IdStatus { get; set; }
        public string? StatusData { get; set; }
    }

    public class Collaborator
    {
        public int IdCollaborator { get; set; }
        public string? CollaboratorName { get; set; }
    }
}

WebUI/WebUI/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Diagnostics;
using WebUI.Models;
using WebUI.Services;

namespace WebUI.Controllers
{
    
    public class TaskController : Controller
    {
        private ApiServices _apiServices = new ApiServices();
        private string _errorMessage;
        private readonly ILogger<TaskController> _logger;
        
        public TaskController(ILogger<TaskController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Collaborator = FillCollaborators(true);
            ViewBag.Priorities = FillPriorities(true);
            ViewBag.Status = FillStatus(true);
            
            List<string> result = _apiServices.GetAllTasks();

            if (result[0] == "1")
            {
                var tasksResults = JsonConvert.DeserializeObject<IEnumerable<Tasks>>(result[1]);
                ViewBag.TasksResults = tasksResults;
                return View();
            }
            else {
                ViewBag.ErrorMessage = result[1];
                return View();
            }
        }
        [HttpPost]
        public ActionResult Index(Tasks tasks)
        {
            //Llena objetos, para crear los select de la vista | (allOption = true) agrega la opcion "TODOS"
            ViewBag.Collaborator = FillCollaborators(true);
            ViewBag.Priorities = FillPriorities(true);
            ViewBag.Status = FillStatus(true);
            
            //Se quitan del ModelState porque se estan en el modelo, pero para la busqueda no son necesarios
            this.ModelState.Remove("IdCollaborator");
            this.ModelState.Remove("Description");
            //Se valida que la fecha final sea mayor a la inicial, sino agregamos la validacion.
            if (tasks.ToDate < tasks.FromDate) {
                this.ModelState.AddModelError("ToDate","Debe ser mayor o igual a la fecha inicial");
            }
            //Cambiar el mensaje de error si la fecha es vacia
            if (tasks.ToDate.ToString() == "1/1/0001 12:00:00 am") {
                this.ModelState.Remove("ToDate");
                this.ModelState.AddModelError("ToDate", "Fecha requerida!");
            }
            if (tasks.FromDate.ToString() == "1/1/0001 12:00:00 am")
            {
                this.ModelState.Remove("FromDate");
                this.ModelState.AddModelError("FromDate", "Fecha requerida!");
            }
            //Verificar si se cumplieron las validaciones y no hay errores
            if (this.ModelState.IsValid)
            {
                List<string> result = _apiServices.GetTasksFiltred(tasks);

                if (result[0] == "1")
                {
                    var tasksResults = JsonConvert.DeserializeObject<IEnumerable<Tasks>>(result[1]);
                    ViewBag.TasksResults = tasksResults;
                    return View(tasks);
                }
                else
                {
                    ViewBag.ErrorMessage = result[1];
                    return View(tasks);
                }
            }
            else
            {
                List<string> result = _apiServices.GetAllTasks();
                var tasksResults = JsonConvert.DeserializeObject<IEnumerable<Tasks>>(result[1]);
                ViewBag.TasksResults = tasksResults;
                return View();
            }
        }

        public IActionResult Insert()
        {
            ViewBag.Collaborator = FillCollaborators(false,true);
            ViewBag.Priorities = FillPriorities();
            ViewBag.Status = FillStatus();
            ViewBag.ErrorMessage = _errorMessage;
            return View();
        }
        [HttpPost]
        public IActionResult Insert(Tasks insert)
        {
            //Remover del modelState IdCollaborador para no tomar el cuenta la validadacion de requerido si su estado es "PENDIENTE"
            if (insert.Status == "PENDIENTE") {
                this.ModelState.Remove("IdCollaborator");
            }
            ViewBag.Collaborator = FillCollaborators(false, true);
            ViewBag.Priorities = FillPriorities();
            ViewBag.Status = FillStatus();
            //Se valida que la fecha final sea mayor a la inicial, sino agregamos la validacion.
            if (insert.ToDate < insert.FromDate)
            {
                this.ModelState.AddModelError("ToDate", "Debe ser mayor o igual a la fecha inicial");
            }
            //Cambiar el mensaje de error si la fecha es vacia
            if (insert.ToDate.ToString() == "1/1/0001 12:00:00 am")
            {
                this.ModelState.Remove("ToDate");
                this.ModelState.AddModelError("ToDate", "Fecha requerida!");
            }
            if (insert.FromDate.ToString() == "1/1/0001 12:00:00 am")
            {
                this.ModelState.Remove("FromDate");
                this.ModelState.AddModelError("FromDate", "Fecha requerida!");
            }

            if (this.ModelState.IsValid)
            {
                List<string> result = _apiServices.InsertTask(insert);

                if (result[0] == "1")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = result[1];
                    return View(insert);
                }
            }
            else
            {
                return View(insert);
            }
            
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Collaborator = FillCollaborators(false, true);
            ViewBag.Priorities = FillPriorities();
            ViewBag.Status = FillStatus();

            List<string> result = _apiServices.GetTask(id);

            if (result[0] == "1")
            {
                var tasksResult = JsonConvert.DeserializeObject<Tasks>(result[1]);
                return View(tasksResult);
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public IActionResult Edit(Tasks edit)
        {
            //Remover del modelState IdCollaborador para no tomar el cuenta la validadacion de requerido si su estado es "PENDIENTE"
            if (edit.Status == "PENDIENTE")
            {
                this.ModelState.Remove("IdCollaborator");
            }
            ViewBag.Collaborator = FillCollaborators(false, true);
            ViewBag.Priorities = FillPriorities();
            ViewBag.Status = FillStatus();
            //Se valida que la fecha final sea mayor a la inicial, sino agregamos la validacion.
            if (edit.ToDate < edit.FromDate)
            {
                this.ModelState.AddModelError("ToDate", "Debe ser mayor o igual a la fecha inicial");
            }
            //Cambiar el mensaje de error si la fecha es vacia
            if (edit.ToDate.ToString() == "1/1/0001 12:00:00 am")
            {
                this.ModelState.Remove("ToDate");
                this.ModelState.AddModelError("ToDate", "Fecha requerida!");
            }
            if (edit.FromDate.ToString() == "1/1/0001 12:00:00 am")
            {
                this.ModelState.Remove("FromDate");
                this.ModelState.AddModelError("FromDate", "Fecha requerida!");
            }

            if (this.ModelState.IsValid)
            {
                List<string> result = _apiServices.EditTask(edit);

                if (result[0] == "1")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = result[1];
                    return View(edit);
                }
            }
            else
            {
                return View(edit);
            }
        }
        public IActionResult Details(int id)
        {
            ViewBag.Collaborator = FillCollaborators(false, true);
            ViewBag.Priorities = FillPriorities();
            ViewBag.Status = FillStatus();

            List<string> result = _apiServices.GetTask(id);

            if (result[0] == "1")
            {
                var tasksResult = JsonConvert.DeserializeObject<Tasks>(result[1]);
                ViewBag.TasksResult = tasksResult;
                return View(tasksResult);
            }
            else
            {
                ViewBag.ErrorMessage = result[1];
                return View();
            }
        }
   
        public IActionResult Delete(int id)
        {
            
            ViewBag.IdTask = id;
            List<string> result = _apiServices.DeleteTask(id);

            if (result[0] == "1")
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrorMessage = result[1];
                return View();
            }
        }

        //Llena la clase Priority, para pasarle los datos del select a la vista
        public List<Priority> FillPriorities(bool allOption=false ) 
        {
            List<Priority> priorityList = new List<Priority>();
            Priority priority = new Priority();
            if (allOption)
            {
                priority.IdPriority = 0;
                priority.PriorityData = "TODOS";
                priorityList.Add(priority);
            }
            priority = new Priority();
            priority.IdPriority = 1;
            priority.PriorityData = "BAJA";
            priorityList.Add(priority);
            priority = new Priority();
            priority.IdPriority = 2;
            priority.PriorityData = "MEDIA";
            priorityList.Add(priority);
            priority = new Priority();
            priority.IdPriority = 3;
            priority.PriorityData = "ALTA";
            priorityList.Add(priority);
            return priorityList;
        }

WebUI/WebUI/Views/Task/Details.cshtml
@model WebUI.Models.Tasks

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<h4>Tarea # @Model.IdTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
                <label asp-for="Description" class="control-label">Descripción</label>
                <input readonly asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCollaborator" class="control-label">Colaborador</label>
                <select readonly asp-for="IdCollaborator" class="form-control" >
                    @{
                        foreach(var item in ViewBag.Collaborator)
                        {
                            <option value="@item.IdCollaborator">@item.CollaboratorName</option>    
                        }
                    }
                }
                </select>
                <span asp-validation-for="IdCollaborator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label">Prioridad</label>
                <select readonly asp-for="Priority" class="form-control">
                @{
                    foreach(var item in ViewBag.Priorities)
                    {
                        <option value="@item.PriorityData">@item.PriorityData</option>
                    }
                }
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label">Estado</label>
                <select readonly asp-for="Status" class="form-control">
                @{
                    foreach(var item in ViewBag.Status)
                    {
                        <option value="@item.StatusData">@item.StatusData</option>
                    }
                }
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromDate" class="control-label">Fecha Inicial</label>
                 @Html.TextBoxFor(m => m.FromDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy", @readonly="true" })
                <span asp-validation-for="FromDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDate" class="control-label">Fecha Final</label>
                 @Html.TextBoxFor(m => m.ToDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy" , @readonly="true" })
                <span asp-validation-for="ToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label">Notas</label>
                <input readonly asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id="message-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="error-message">@ViewBag.ErrorMessage</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div>
    </br>
    <a asp-action="Index">Atrás</a>
</div>

WebUI/WebUI/Views/Task/Edit.cshtml
@model WebUI.Models.Tasks

@{
    ViewData["Title"] = "Editar";
    
}

<h1>Editar</h1>

<h4>Tarea # @Model.IdTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @Html.Hidden("IdTask")
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
                <label asp-for="Description" class="control-label">Descripción</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCollaborator" class="control-label">Colaborador</label>
                <select asp-for="IdCollaborator" class="form-control" >
                    @{
                        foreach(var item in ViewBag.Collaborator)
                        {
                            <option value="@item.IdCollaborator">@item.CollaboratorName</option>    
                        }
                    }
                }
                </select>
                <span asp-validation-for="IdCollaborator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label">Prioridad</label>
                <select asp-for="Priority" class="form-control">
                @{
                    foreach(var item in ViewBag.Priorities)
                    {
                        <option value="@item.PriorityData">@item.PriorityData</option>
                    }
                }
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label">Estado</label>
                <select asp-for="Status" class="form-control">
                @{
                    foreach(var item in ViewBag.Status)
                    {
                        <option value="@item.StatusData">@item.StatusData</option>
                    }
                }
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromDate" class="control-label">Fecha Inicial</label>
                @Html.TextBoxFor(m => m.FromDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy" })
                <span asp-validation-for="FromDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDate" class="control-label">Fecha Final</label>
                @Html.TextBoxFor(m => m.ToDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy"})
                <span asp-validation-for="ToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label">Notas</label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            </br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id="message-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="error-message">@ViewBag.ErrorMessage</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div>
    </br>
    <a asp-action="Index">Atrás</a>
</div>

WebUI/WebUI/Views/Task/Index.cshtml
@model WebUI.Models.Tasks
@{
    ViewData["Title"] = "Listado de Tareas";
}

<h1>Listado de Tareas</h1>

<form asp-controller="Task" asp-action="Index">
    <p>
        <hr/>
        <div class="row">
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="IdCollaborator" class="control-label">Colaborador</label>
                    <select asp-for="IdCollaborator" class="form-control" >
                    @{
                        foreach(var item in ViewBag.Collaborator)
                        {
                                    <option value="@item.IdCollaborator">@item.CollaboratorName</option>
                        }
                    }
                    </select>
                    <span asp-validation-for="IdCollaborator" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="Priority" class="control-label">Prioridad</label>
                    <select asp-for="Priority" class="form-control">
                    @{
                        foreach(var item in ViewBag.Priorities)
                        {
                                    <option value="@item.PriorityData">@item.PriorityData</option>
                        }
                    }
                    </select>
                    <span asp-validation-for="Priority" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="Status" class="control-label">Estado</label>
                    <select  asp-for="Status" class="form-control">
                    @{
                        foreach(var item in ViewBag.Status)
                        {
                                    <option value="@item.StatusData">@item.StatusData</option>
                        }
                    }
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="FromDate" class="control-label">Fecha Inicial</label>
                    @*<input asp-for="FromDate" class="form-control" />*@
                    @Html.TextBoxFor(m => m.FromDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy" })
                    <span asp-validation-for="FromDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="ToDate" class="control-label">Fecha Final</label>
                    @Html.TextBoxFor(m => m.ToDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @placeholder = "dd/mm/yyyy" })
                    <span asp-validation-for="ToDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                 <div class="form-group">
                    <label class="control-label"></label>
                    <div class="d-flex">
                    <input type="submit" value="Filtrar" class="form-control btn btn-sm btn-primary"/> &nbsp;
                    <input onclick="quitarFiltro()"  value="Quitar filtro" class="form-control btn btn-sm btn-secondary"/>  

                    </div>
              
                </div>  
            </div>
        </div>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Descripción
            </th>
            <th>
                Nombre Colaborador
            </th>
            <th>
                Prioridad
            </th>
            <th>
                Estado
            </th>
            <th>
                Fecha Inicial
            </th>
            <th>
                Fecha Final
            </th>
            <th>
                <a asp-action="Insert" class="btn btn-success" title="Crear nueva tarea"><i class="fa-regular fa-square-plus"></i>  Nueva tarea</a> 
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @if (ViewBag.TasksResults != null)
    {
        @foreach (var item in ViewBag.TasksResults) {
        <tr>
            <td>
                @item.IdTask
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.CollaboratorName
            </td>
            <td>
                @item.Priority
            </td>
            <td>
                @item.Status
            </td>
            <td>
                @item.FromDate.ToString("dd-MM-yyyy")
            </td>
            <td>
                @item.ToDate.ToString("dd-MM-yyyy")
            </td>
            <td>
                <a onclick="editValidate(@item.IdTask,'@item.Status')" class="btn btn-primary" title="Editar"><i class="fa-regular fa-pen-to-square"></i></a>  
                <a asp-action="Details" class="btn btn-info" asp-route-id="@item.IdTask" title="Ver Detalles"><i class="fa-regular fa-eye"></i></a> 
                <a onclick="deleteConfirm(@item.IdTask,'@item.Status')" class="btn btn-danger" title="Eliminar"><i class="fa-regular fa-trash-can"></i></a>
            </td>
        </tr>
    }
}  
        <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="confirmation-modal">
            <div class="modal-dialog ">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Advertencia</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p id="modalMessage"></p>
                    </div>
                    <div class="modal-footer">
                        <a asp-action="Delete" class="btn btn-danger" id="modal-btn-si" asp-route-id="">Si</a>
                        <a asp-action="" class="btn btn-primary" id="modal-btn-no" asp-route-id="">No</a> 
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id="message-modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Error</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p id="error-message">@ViewBag.ErrorMessage</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ok</button>
                    </div>
                </div>
            </div>
        </div>

    </tbody>
</table>
<script type="text/javascript" >

    function quitarFiltro() {
        location.href = "";
    }
    function deleteConfirm(id, status)
    {
        if (status == "EN PROCESO") {
            $("#error-message").text("Solo se puede eliminar tareas siempre y cuando no esté EN PROCESO");
            $("#message-modal").modal('show');
        }
        else {
            $("#modalMessage").text("¿Está seguro que desea eliminar la tarea #"+id+" ?");
            $("#confirmation-modal").modal('show');
            var newhref=$("#modal-btn-si").attr('href') + '/' + id ;     
            $("#modal-btn-si").attr("href", newhref);
            $("#modal-btn-no").on("click", function(){
                $("#confirmation-modal").modal('hide');
            });
        }
    }
    function editValidate(id, status)
    {
        if (status == "FINALIZADA") {
            $("#error-message").text("Solo se puede editar tareas PENDIENTES o EN PROCESO");
            $("#message-modal").modal('show');
        }
        else {
            location.href = "Task/Edit/" + id;
        }
    }
            
</script>